### ISSUE TITLE
evm>native transfer error

### ISSUE THREAD

**Issue by DomFeng** [FindoraNetwork/platform#138]
### Problem Description
>description:
evm>native 转账，交易成功，evm账户扣了0.01手续费，但是转账金额evm账户没有扣除，native账户没有增加

>Screenshots:
![image](https://user-images.githubusercontent.com/61138066/144363919-129cfa1e-930c-44e7-a4e2-ba8f0220358b.png)

### Environmental information
>operating system:
unbuntu

>service:
findora

>Code version:
mock-mainnet
Build: testnet-evm-v0.2.7a 2021-11-26

### Steps to reproduce
>1、evm账户余额2.409999fra

>2、evm>native转账2.409999fra

**Comment by ws4charlie** [comment]
@tiannian @jianwel @DomFeng  Hi Guys. Thanks for finding this good edge case. The transfer failure can be replicated locally and it is expected behaviour for backend. We can consider optimizing front-end user experience in this edge case.

picture-1: Before transfer to UTXO, my balance was 2.4 FRA
![image](https://user-images.githubusercontent.com/34498985/144482110-480c038a-3d7d-4ebb-9184-eb18647fbd18.png)

picture-2: Transfer page. Note: Amount+Fee = 2.41 which is greater than my balance 2.4
![image](https://user-images.githubusercontent.com/34498985/144482278-ce92f7fe-3606-44a2-ba86-c4ca8cd5af7b.png)

picture-3: Transfer submitted successfully.
![image](https://user-images.githubusercontent.com/34498985/144482503-90191ebe-59e5-47d0-a719-db8c4cade19c.png)

picture-4: Transfer failed at the backend. See logs below.
![image](https://user-images.githubusercontent.com/34498985/144482894-a3fb28c9-be1c-4a88-a39e-8cede28a76b0.png)

Conclusion:
This failure was expected behaviour for backend. To give a better experience at frontend,  Wallet GUI should ideally allow 2.39(2.4-0.01) FRA as maximum to be transferred. Similar to what MetaMask does below.
![image](https://user-images.githubusercontent.com/34498985/144483657-4f0a00a7-5ea2-4258-9e7c-1b032512922a.png)

**Comment by ws4charlie** [comment]
@HelloRickey This was fixed, right?

**Comment by ws4charlie** [comment]
I verified this bug fix using latest wallet installer 0.3.4. It's fixed already. Thanks @HelloRickey
